name: nerf-tex
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip=20.2.4
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pydot=1.4.1
  - tqdm=4.50.2
  - tensorflow-gpu=2.4.1
  - scikit-image=0.17.2
  - cython=0.29.21