FROM nytimes/blender:2.92-gpu-ubuntu18.04

WORKDIR /workspace

# Usage: docker run -v <path to this repo>:/workspace -v <path do dataset output location>:/datasets <img name> sh data/create_dataset.sh <location to .blend file> <location to config file>